version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
  - source: /systemd/simple-app.service
    destination: /etc/systemd/system
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/check_service.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root
